import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>NBA 2K calc 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/nba-data-app-logo-white.png" />
      </Head>

      <div>Maybe tomorrow.</div>

    </div>
  )
}
